/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetoLp1.Interface;


import java.awt.Color;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import projetoLp1.Interface.Model.ClasseDados;
import javax.swing.JOptionPane;

/**
 *
 * @author thiagofsr
 */
public class DadosPessoais extends javax.swing.JInternalFrame {

    /**
     * Creates new form DadosPessoais
     */
    public static void branco (){
        txtEmail.setBackground(Color.white);
        txtCPF.setBackground(Color.white);
        txtTelefone.setBackground(Color.white);
        txtRegProfissional.setBackground(Color.white);
        txtEndereco.setBackground(Color.white);
        txtNome.setBackground(Color.white);
    }
    
    public DadosPessoais() {
        initComponents();
        addInternalFrameListener(new InternalFrameAdapter(){
            @Override
            public void internalFrameClosing(InternalFrameEvent e) {
                // do something  
                TelaPrincipal.gerenciaTela(6);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRegProfissional = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnAvancar = new javax.swing.JButton();
        boxDDD = new javax.swing.JComboBox<>();
        boxEmail = new javax.swing.JComboBox<>();

        setClosable(true);

        jLabel1.setText("Nome:");

        txtNome.setToolTipText("");

        jLabel2.setText("Endereço:");

        jLabel3.setText("Telefone:");

        jLabel4.setText("CPF:");

        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });

        jLabel5.setText("R.P:");

        jLabel6.setText("Email:");

        btnAvancar.setText("Avançar");
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });

        boxDDD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "69", "71", "73", "74", "75", "76", "77", "79", "81", "82", "83", "84", "85", "86", "87", "88", "89" }));
        boxDDD.setSelectedIndex(10);

        boxEmail.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "@hotmail.com", "@outlook.com", "@yahoo.com", "@yahoo.com.br", "@gmail.com", "@live.com", "@msn.com", "Outro (Digite ao lado)" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boxDDD, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtTelefone))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAvancar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(boxEmail, 0, 159, Short.MAX_VALUE))
                            .addComponent(txtEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCPF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRegProfissional, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxDDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRegProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnAvancar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
        
        branco();
        // VERIFICAR SE TODOS OS CAMPOS TEM INFORMAÇÕES CERTAS
        boolean checked = true; // Verifica se os dados foram preenchidos corretamente
        
        //Verificando email, caso ok, atribui o valor.
        if(txtEmail != null && !txtEmail.getText().isEmpty()){
            
            String email = txtEmail.getText();
            
            if(boxEmail.getSelectedItem().toString().equals("Outro (Digite ao lado)") == false){ //Caso alguma opção seja selecionada
                for(int i = 0; i< txtEmail.getText().length(); i++){ //Percorre a string procurando "@"
                    if(email.charAt(i) == '@'){ // Se encontrar, pega String até o @
                        email = email.substring(0,i);
                        break;
                    }
                }
                email += boxEmail.getSelectedItem().toString(); // Após pegar Substring, adiciona o tipo de email das opções
            }else{
                boolean achou = false; // Se a opção for "Outro"
                for(int i = 0; i< txtEmail.getText().length(); i++){ // Percorre a string procurando "@"
                    if(email.charAt(i) == '@' && i > 0){ // Se encontrar, o email é válido
                        achou = true;
                        break;
                    }
                }
                if(achou == false){
                    txtEmail.setBackground(new java.awt.Color(255, 51, 51));
                    checked = false;
                    // Se não encontrar, Email inválido!
                }
                    
            }

            dados.setEmail(email);
        }else{
            txtEmail.setBackground(new java.awt.Color(255, 51, 51));
            checked = false;
        }
        
        //Verificando cpf, caso ok, atribui o valor.
        if(txtCPF != null && !txtCPF.getText().isEmpty()){
     
            for(int i = 0; i <txtCPF.getText().length(); i++){ // Percorre todo o campo do CPF
                char c = txtCPF.getText().charAt(i);
                if( !Character.isDigit(c)){ // Se for diferente de um número, Checked recebe False
                    txtCPF.setBackground(new java.awt.Color(255, 51, 51));
                    checked = false;
                    break;
                }
            }
            dados.setCpf(txtCPF.getText());
            
            
        }else{
            txtCPF.setBackground(new java.awt.Color(255, 51, 51));
            checked = false;
        }
        
        //Verificando Endereço, caso ok, atribui o valor.
        if(txtEndereco != null && !txtEndereco.getText().isEmpty()){
            dados.setEndereço(txtEndereco.getText());
        }else{
            txtEndereco.setBackground(new java.awt.Color(255, 51, 51));
            checked = false;
        }
        
        //Verificando Nome, caso ok, atribui o valor.
        if(txtNome != null && !txtNome.getText().isEmpty()){
            dados.setNome(txtNome.getText().toUpperCase()); // NOME MAIUSCULO
        }else{
            txtNome.setBackground(new java.awt.Color(255, 51, 51));
            checked = false;
        }
        
        //Verificando RegProfissional, caso ok, atribui o valor.
        if(txtRegProfissional != null && !txtRegProfissional.getText().isEmpty()){
            dados.setRegistro(txtRegProfissional.getText());
        }else{
            txtRegProfissional.setBackground(new java.awt.Color(255, 51, 51));
            checked = false;
        }
        
        //Verificando Telefone, caso ok, atribui o valor.
        if(txtTelefone != null && !txtTelefone.getText().isEmpty()){
            
            for(int i = 0; i <txtTelefone.getText().length(); i++){// Percorre todo o campo de telefone
                char c = txtTelefone.getText().charAt(i);
                if( Character.isDigit(c) == false){ // Se for diferente de um numero, checked recebe False
                    txtTelefone.setBackground(new java.awt.Color(255, 51, 51));
                    checked = false;
                    break;
                }
            }            
            dados.setTelefone(txtTelefone.getText());
        }else{
            txtTelefone.setBackground(new java.awt.Color(255, 51, 51));
            checked = false;
        }  
             
        if(checked){          
          TelaPrincipal.gerenciaTela(2);
        }else{
            JOptionPane.showMessageDialog(this, "Verifique os dados e tente novamente!", "Atenção", WIDTH);
        }      
        
    }//GEN-LAST:event_btnAvancarActionPerformed

    
    private ClasseDados dados = new ClasseDados();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxDDD;
    private javax.swing.JComboBox<String> boxEmail;
    private javax.swing.JButton btnAvancar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private static javax.swing.JTextField txtCPF;
    private static javax.swing.JTextField txtEmail;
    private static javax.swing.JTextField txtEndereco;
    private static javax.swing.JTextField txtNome;
    private static javax.swing.JTextField txtRegProfissional;
    private static javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
